# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=1024', '--enforce-all']
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
# Python
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      files: \.py$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.291
    hooks:
    - id: ruff
      args: ["--fix"]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
    -   id: black-jupyter
